server:
    port: 3344

spring:
    application:
        name: cloud-config-server
    cloud:
        config:
            server:
                git:
                    uri: git@github.com/szjacky8868/springcloud-config.git
                    search-paths:
                        -   springcloud-config
            label: master

eureka:
    instance:
        hostname: ${spring.cloud.client.ip-address}:${server.port}
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
